name: Create Missing Directories

on:
  workflow_dispatch:  # 手動実行も可能にする
  workflow_run:
    workflows: ["Update clasp-list.txt"]  # この名前のワークフローの完了をトリガーにする
    types:
      - completed

jobs:
  run-script:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gas-pull branch
        uses: actions/checkout@v4
        with:
          ref: gas-pull
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run script
        run: |
          if [ ! -f clasp-list.txt ]; then
            echo "Error: clasp-list.txt not found in the repository root."
            exit 1
          fi

          python3 create_missing_scriptid_dirs.py clasp-list.txt
