name: Sync from GAS

# Ensure GITHUB_TOKEN can write to the repo
permissions:
  contents: write

on:
  schedule:
    - cron: '0 3 * * *'  # Run daily at 03:00 UTC (12:00 JST)
  workflow_dispatch:

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      # Always check out the gas-pull branch, never main
      - name: Checkout gas-pull branch
        uses: actions/checkout@v3
        with:
          ref: gas-pull
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Restore clasp credentials
        run: |
          echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json

      - name: Pull true/false quiz
        working-directory: moodle-true-false-quiz-validator
        run: clasp pull

      - name: Pull multiple-choice quiz
        working-directory: moodle-multichoice-question-validator
        run: clasp pull

      - name: Pull show-google-tasks
        working-directory: show-google-tasks
        run: clasp pull

      - name: Pull document-saver
        working-directory: document-saver
        run: clasp pull

      - name: Pull ime-dictionary-aggregator
        working-directory: ime-dictionary-aggregator
        run: clasp pull

      - name: Pull ime-dictionary-library
        working-directory: ime-dictionary-library
        run: clasp pull

      - name: Commit & Push changes if any
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add moodle-true-false-quiz-validator/ moodle-multichoice-question-validator/ show-google-tasks/ document-saver/ ime-dictionary-aggregator/ ime-dictionary-library/
            git commit -m "chore: daily sync GAS → gas-pull"
            git push origin gas-pull
          else
            echo "No changes detected, skipping commit"
          fi
