name: Sync from GAS

# GITHUB_TOKEN に書き込み権限を付与
permissions:
  contents: write

on:
  schedule:
    - cron: '0 3 * * *' # 毎日03:00（UTC）に実行（日本時間で12:00）
  workflow_dispatch:

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      # gas-pull ブランチをチェックアウト
      - name: Checkout gas-pull branch
        uses: actions/checkout@v3
        with:
          ref: gas-pull
          persist-credentials: true  # GITHUB_TOKEN を保持して push に使う
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Restore clasp credentials
        run: |
          echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json

      - name: Pull latest GAS code
        run: |
          cd moodle-true-false-quiz-validator/
          clasp pull

      - name: Pull latest GAS code
        run: |
          cd moodle-multichoice-question-validator/
          clasp pull

      - name: Commit & Push changes if any
        run: |
          cd moodle-true-false-quiz-validator/
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: daily sync GAS → gas-pull"
            # gas-pull ブランチにプッシュ
            git push origin gas-pull
          else
            echo "No changes detected, skipping commit"
          fi
